// Generated by @svg-animated-icons/cli
// Framework-agnostic SVG path morph engine.
// You own this file — edit it freely.

export type MorphOptions = {
  duration?: number;
  easing?: (t: number) => number;
};

export type MorphHandle = {
  cancel: () => void;
};

const NUMBER_RE = /-?\d+(?:\.\d+)?(?:e[-+]?\d+)?/gi;

function parseNumbers(d: string): number[] {
  const matches = d.match(NUMBER_RE);
  return matches ? matches.map(Number) : [];
}

function commandSignature(d: string): string {
  const cmds = d.match(/[a-zA-Z]/g);
  return cmds ? cmds.join("") : "";
}

export function interpolatePath(fromD: string, toD: string, t: number): string {
  if (commandSignature(fromD) !== commandSignature(toD)) {
    throw new Error("Cannot interpolate paths with different command sequences");
  }
  const fromNums = parseNumbers(fromD);
  const toNums = parseNumbers(toD);
  if (fromNums.length !== toNums.length) {
    throw new Error("Cannot interpolate paths with different number counts");
  }

  let i = 0;
  return fromD.replace(NUMBER_RE, () => {
    const a = fromNums[i] ?? 0;
    const b = toNums[i] ?? 0;
    i++;
    const value = a + (b - a) * t;
    return formatNumber(value);
  });
}

function formatNumber(n: number): string {
  return Number.isInteger(n) ? n.toString() : n.toFixed(3).replace(/\.?0+$/, "");
}

function easeOutCubic(t: number): number {
  return 1 - Math.pow(1 - t, 3);
}

export function animateMorph(
  pathEl: SVGPathElement,
  fromD: string,
  toD: string,
  opts: MorphOptions = {},
): MorphHandle {
  const duration = opts.duration ?? 280;
  const easing = opts.easing ?? easeOutCubic;
  const start = performance.now();
  let frame = 0;
  let cancelled = false;

  function tick(now: number): void {
    if (cancelled) return;
    const elapsed = now - start;
    const t = Math.min(1, elapsed / duration);
    const eased = easing(t);
    pathEl.setAttribute("d", interpolatePath(fromD, toD, eased));
    if (t < 1) {
      frame = requestAnimationFrame(tick);
    }
  }

  frame = requestAnimationFrame(tick);

  return {
    cancel(): void {
      cancelled = true;
      cancelAnimationFrame(frame);
    },
  };
}
