// Generated by @svg-animated-icons/cli
// You own this file — edit it freely.

import { useEffect, useRef } from "react";
import { animateMorph } from "../../lib/svg-icons/morph";

type State = "{{fromName}}" | "{{toName}}";

const FROM_PATHS: Record<string, string> = {
{{fromPaths}}
};

const TO_PATHS: Record<string, string> = {
{{toPaths}}
};

type Props = {
  state: State;
  duration?: number;
  className?: string;
};

export function {{ComponentName}}({ state, duration = 280, className }: Props) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const stateRef = useRef<State>(state);

  useEffect(() => {
    const prev = stateRef.current;
    if (prev === state) return;
    stateRef.current = state;

    const svg = svgRef.current;
    if (!svg) return;

    const paths = svg.querySelectorAll<SVGPathElement>("path[data-part]");
    const animations = Array.from(paths).map((pathEl) => {
      const id = pathEl.dataset.part ?? "";
      const fromMap = state === "{{toName}}" ? FROM_PATHS : TO_PATHS;
      const toMap = state === "{{toName}}" ? TO_PATHS : FROM_PATHS;
      const fromD = fromMap[id];
      const toD = toMap[id];
      if (!fromD || !toD) return null;
      return animateMorph(pathEl, fromD, toD, { duration });
    });

    return () => {
      for (const a of animations) a?.cancel();
    };
  }, [state, duration]);

  return (
    <svg
      ref={svgRef}
      xmlns="http://www.w3.org/2000/svg"
      className={["{{className}}", className ?? ""].filter(Boolean).join(" ")}
      viewBox="{{viewBox}}"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
    >
{{initialPaths}}
    </svg>
  );
}
