// Generated by @svg-animated-icons/cli
// You own this file — edit it freely.

import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  effect,
  inject,
  input,
  viewChild,
} from "@angular/core";
import { animateMorph, type MorphHandle } from "../../lib/svg-icons/morph";

type State = "{{fromName}}" | "{{toName}}";

const FROM_PATHS: Record<string, string> = {
{{fromPaths}}
};

const TO_PATHS: Record<string, string> = {
{{toPaths}}
};

@Component({
  selector: "ai-{{fromName}}-{{toName}}-morph",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <svg
      #svgEl
      xmlns="http://www.w3.org/2000/svg"
      class="{{className}}"
      viewBox="{{viewBox}}"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
{{initialPaths}}
    </svg>
  `,
})
export class {{ComponentName}} {
  state = input.required<State>();
  duration = input<number>(280);

  private svgRef = viewChild<ElementRef<SVGSVGElement>>("svgEl");
  private handles: MorphHandle[] = [];
  private prev: State | null = null;

  constructor() {
    inject(DestroyRef).onDestroy(() => {
      for (const h of this.handles) h.cancel();
    });

    effect(() => {
      const next = this.state();
      const prev = this.prev;
      this.prev = next;
      if (prev === null || prev === next) return;

      const svg = this.svgRef()?.nativeElement;
      if (!svg) return;

      for (const h of this.handles) h.cancel();
      this.handles = [];

      const paths = svg.querySelectorAll<SVGPathElement>("path[data-part]");
      for (const pathEl of Array.from(paths)) {
        const id = pathEl.dataset["part"] ?? "";
        const fromMap = next === "{{toName}}" ? FROM_PATHS : TO_PATHS;
        const toMap = next === "{{toName}}" ? TO_PATHS : FROM_PATHS;
        const fromD = fromMap[id];
        const toD = toMap[id];
        if (!fromD || !toD) continue;
        this.handles.push(animateMorph(pathEl, fromD, toD, { duration: this.duration() }));
      }
    });
  }
}
