// Generated by @svg-animated-icons/cli
// You own this file — edit it freely.

import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  inject,
  input,
  output,
  signal,
} from "@angular/core";

@Component({
  selector: "ai-{{fromName}}-{{toName}}-swap",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      class="ai-swap ai-{{fromName}}-{{toName}}-swap"
      [attr.aria-label]="ariaLabel() ?? (active() ? '{{toName}}' : '{{fromName}}')"
      [attr.data-state]="active() ? '{{toName}}' : '{{fromName}}'"
      (click)="handleClick()"
    >
      <span class="ai-swap-layer ai-swap-from">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="ai-{{fromName}}-icon"
          viewBox="{{fromViewBox}}"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          {{fromSvgInner}}
        </svg>
      </span>
      <span class="ai-swap-layer ai-swap-to">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="ai-{{toName}}-icon"
          viewBox="{{toViewBox}}"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          {{toSvgInner}}
        </svg>
      </span>
    </button>
  `,
  styles: [
    `
.ai-swap {
  background: none;
  border: none;
  padding: 0;
  margin: 0;
  cursor: pointer;
  font: inherit;
  color: inherit;
  position: relative;
  display: inline-flex;
  width: 1em;
  height: 1em;
  line-height: 0;
}
.ai-swap .ai-swap-layer {
  position: absolute;
  inset: 0;
  display: inline-flex;
  transition: opacity 200ms ease, transform 200ms ease;
}
.ai-swap[data-state="{{fromName}}"] .ai-swap-from { opacity: 1; transform: scale(1); }
.ai-swap[data-state="{{fromName}}"] .ai-swap-to   { opacity: 0; transform: scale(0.8); pointer-events: none; }
.ai-swap[data-state="{{toName}}"]   .ai-swap-from { opacity: 0; transform: scale(0.8); pointer-events: none; }
.ai-swap[data-state="{{toName}}"]   .ai-swap-to   { opacity: 1; transform: scale(1); }
{{fromCss}}
{{toCss}}
    `,
  ],
})
export class {{ComponentName}} {
  resetMs = input<number>(1500);
  ariaLabel = input<string | undefined>(undefined);
  activate = output<void>();

  active = signal(false);
  private timeoutHandle: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    inject(DestroyRef).onDestroy(() => {
      if (this.timeoutHandle) clearTimeout(this.timeoutHandle);
    });
  }

  handleClick(): void {
    if (this.active()) return;
    this.activate.emit();
    this.active.set(true);
    if (this.resetMs() > 0) {
      this.timeoutHandle = setTimeout(() => this.active.set(false), this.resetMs());
    }
  }
}
