// Generated by @svg-animated-icons/cli
// You own this file — edit it freely.

import { ChangeDetectionStrategy, Component, input } from "@angular/core";

@Component({
  selector: "ai-{{iconName}}",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="{{baseClass}}"
      [class.no-hover]="disableHover()"
      viewBox="{{viewBox}}"
      fill="none"
    >
      {{svgInner}}
    </svg>
  `,
  styles: [
    `
{{css}}
    `,
  ],
})
export class {{ComponentName}} {
  disableHover = input<boolean>(false);
}
