// Generated by @svg-animated-icons/cli
// You own this file — edit it freely.

import React from "react";

type Props = {
  disableHover?: boolean;
  className?: string;
};

export function {{ComponentName}}({ disableHover, className }: Props) {
  const classes = [
    "{{baseClass}}",
    disableHover ? "no-hover" : "",
    className ?? "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <>
      <style>{`
{{css}}
`}</style>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        className={classes}
        viewBox="{{viewBox}}"
        fill="none"
      >
        {{svgInner}}
      </svg>
    </>
  );
}
