// Generated by @svg-animated-icons/cli
// You own this file — edit it freely.

"use client";

import React, { useEffect, useRef, useState } from "react";

type Props = {
  onActivate?: () => void;
  resetMs?: number;
  className?: string;
  ariaLabel?: string;
};

export function {{ComponentName}}({ onActivate, resetMs = 1500, className, ariaLabel }: Props) {
  const [active, setActive] = useState(false);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  function handleClick() {
    if (active) return;
    onActivate?.();
    setActive(true);
    if (resetMs > 0) {
      timeoutRef.current = setTimeout(() => setActive(false), resetMs);
    }
  }

  return (
    <button
      type="button"
      onClick={handleClick}
      aria-label={ariaLabel ?? (active ? "{{toName}}" : "{{fromName}}")}
      data-state={active ? "{{toName}}" : "{{fromName}}"}
      className={["ai-swap", "ai-{{fromName}}-{{toName}}-swap", className ?? ""]
        .filter(Boolean)
        .join(" ")}
    >
      <style>{`
.ai-swap {
  background: none;
  border: none;
  padding: 0;
  margin: 0;
  cursor: pointer;
  font: inherit;
  color: inherit;
  position: relative;
  display: inline-flex;
  width: 1em;
  height: 1em;
  line-height: 0;
}
.ai-swap .ai-swap-layer {
  position: absolute;
  inset: 0;
  display: inline-flex;
  transition: opacity 200ms ease, transform 200ms ease;
}
.ai-swap[data-state="{{fromName}}"] .ai-swap-from { opacity: 1; transform: scale(1); }
.ai-swap[data-state="{{fromName}}"] .ai-swap-to   { opacity: 0; transform: scale(0.8); pointer-events: none; }
.ai-swap[data-state="{{toName}}"]   .ai-swap-from { opacity: 0; transform: scale(0.8); pointer-events: none; }
.ai-swap[data-state="{{toName}}"]   .ai-swap-to   { opacity: 1; transform: scale(1); }
{{fromCss}}
{{toCss}}
`}</style>
      <span className="ai-swap-layer ai-swap-from">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="ai-{{fromName}}-icon"
          viewBox="{{fromViewBox}}"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          {{fromSvgInner}}
        </svg>
      </span>
      <span className="ai-swap-layer ai-swap-to">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="ai-{{toName}}-icon"
          viewBox="{{toViewBox}}"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          {{toSvgInner}}
        </svg>
      </span>
    </button>
  );
}
