<!-- Generated by @svg-animated-icons/cli -->
<!-- You own this file — edit it freely. -->

<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from "vue";
import { animateMorph, type MorphHandle } from "../../lib/animated-icons/morph";

type State = "{{fromName}}" | "{{toName}}";

const props = withDefaults(
  defineProps<{
    state: State;
    duration?: number;
  }>(),
  { duration: 280 },
);

const FROM_PATHS: Record<string, string> = {
{{fromPaths}}
};

const TO_PATHS: Record<string, string> = {
{{toPaths}}
};

const svgRef = ref<SVGSVGElement | null>(null);
let handles: MorphHandle[] = [];

watch(
  () => props.state,
  (next, prev) => {
    if (next === prev) return;
    const svg = svgRef.value;
    if (!svg) return;

    for (const h of handles) h.cancel();
    handles = [];

    const paths = svg.querySelectorAll<SVGPathElement>("path[data-part]");
    for (const pathEl of Array.from(paths)) {
      const id = pathEl.dataset.part ?? "";
      const fromMap = next === "{{toName}}" ? FROM_PATHS : TO_PATHS;
      const toMap = next === "{{toName}}" ? TO_PATHS : FROM_PATHS;
      const fromD = fromMap[id];
      const toD = toMap[id];
      if (!fromD || !toD) continue;
      handles.push(animateMorph(pathEl, fromD, toD, { duration: props.duration }));
    }
  },
);

onBeforeUnmount(() => {
  for (const h of handles) h.cancel();
});
</script>

<template>
  <svg
    ref="svgRef"
    xmlns="http://www.w3.org/2000/svg"
    class="{{className}}"
    viewBox="{{viewBox}}"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
{{initialPaths}}
  </svg>
</template>
