<!-- Generated by @svg-animated-icons/cli -->
<!-- You own this file — edit it freely. -->

<script setup lang="ts">
import { onUnmounted, ref } from "vue";

const props = withDefaults(
  defineProps<{
    resetMs?: number;
    ariaLabel?: string;
  }>(),
  { resetMs: 1500 },
);

const emit = defineEmits<{ activate: [] }>();

const active = ref(false);
let timeoutHandle: ReturnType<typeof setTimeout> | null = null;

function handleClick(): void {
  if (active.value) return;
  emit("activate");
  active.value = true;
  if (props.resetMs > 0) {
    timeoutHandle = setTimeout(() => {
      active.value = false;
    }, props.resetMs);
  }
}

onUnmounted(() => {
  if (timeoutHandle) clearTimeout(timeoutHandle);
});
</script>

<template>
  <button
    type="button"
    :class="['ai-swap', 'ai-{{fromName}}-{{toName}}-swap']"
    :aria-label="ariaLabel ?? (active ? '{{toName}}' : '{{fromName}}')"
    :data-state="active ? '{{toName}}' : '{{fromName}}'"
    @click="handleClick"
  >
    <span class="ai-swap-layer ai-swap-from">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="ai-{{fromName}}-icon"
        viewBox="{{fromViewBox}}"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        {{fromSvgInner}}
      </svg>
    </span>
    <span class="ai-swap-layer ai-swap-to">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="ai-{{toName}}-icon"
        viewBox="{{toViewBox}}"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        {{toSvgInner}}
      </svg>
    </span>
  </button>
</template>

<style scoped>
.ai-swap {
  background: none;
  border: none;
  padding: 0;
  margin: 0;
  cursor: pointer;
  font: inherit;
  color: inherit;
  position: relative;
  display: inline-flex;
  width: 1em;
  height: 1em;
  line-height: 0;
}
.ai-swap .ai-swap-layer {
  position: absolute;
  inset: 0;
  display: inline-flex;
  transition: opacity 200ms ease, transform 200ms ease;
}
.ai-swap[data-state="{{fromName}}"] .ai-swap-from { opacity: 1; transform: scale(1); }
.ai-swap[data-state="{{fromName}}"] .ai-swap-to   { opacity: 0; transform: scale(0.8); pointer-events: none; }
.ai-swap[data-state="{{toName}}"]   .ai-swap-from { opacity: 0; transform: scale(0.8); pointer-events: none; }
.ai-swap[data-state="{{toName}}"]   .ai-swap-to   { opacity: 1; transform: scale(1); }
{{fromCss}}
{{toCss}}
</style>
