<!-- Generated by @svg-animated-icons/cli -->
<!-- You own this file — edit it freely. -->

<script setup lang="ts">
defineProps<{
  disableHover?: boolean;
}>();
</script>

<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    :class="['{{baseClass}}', disableHover ? 'no-hover' : '']"
    viewBox="{{viewBox}}"
    fill="none"
  >
    {{svgInner}}
  </svg>
</template>

<style scoped>
{{css}}
</style>
