import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type Framework,
  type RegistryEntry,
  renderIconForFramework,
  toComponentName,
} from "@svg-animated-icons/codegen";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REGISTRY_DIR = join(__dirname, "..", "..", "apps", "docs", "public", "r");
const ROOT_PACKAGES = join(__dirname, "..");

type PackageSpec = {
  framework: Framework;
  dir: string;
  iconExt: string;
  barrelPath: string;
  barrelLine: (entry: RegistryEntry, component: string) => string;
};

const PACKAGES: PackageSpec[] = [
  {
    framework: "react",
    dir: join(ROOT_PACKAGES, "react"),
    iconExt: "tsx",
    barrelPath: "src/index.ts",
    barrelLine: (entry, component) => `export { ${component} } from "./icons/${entry.name}.js";`,
  },
  {
    framework: "vue",
    dir: join(ROOT_PACKAGES, "vue"),
    iconExt: "vue",
    barrelPath: "src/index.ts",
    barrelLine: (entry, component) =>
      `export { default as ${component} } from "./icons/${entry.name}.vue";`,
  },
  {
    framework: "angular",
    dir: join(ROOT_PACKAGES, "angular"),
    iconExt: "component.ts",
    barrelPath: "src/public-api.ts",
    barrelLine: (entry, component) =>
      `export { ${component} } from "./icons/${entry.name}.component";`,
  },
];

async function loadRegistry(): Promise<RegistryEntry[]> {
  const files = await readdir(REGISTRY_DIR);
  const iconFiles = files.filter((f) => f.endsWith(".json") && f !== "index.json").sort();
  const entries = await Promise.all(
    iconFiles.map(async (f) => {
      const content = await readFile(join(REGISTRY_DIR, f), "utf8");
      return JSON.parse(content) as RegistryEntry;
    }),
  );
  return entries;
}

async function generatePackage(spec: PackageSpec, entries: RegistryEntry[]): Promise<void> {
  const iconsDir = join(spec.dir, "src", "icons");
  await rm(iconsDir, { recursive: true, force: true });
  await mkdir(iconsDir, { recursive: true });

  const barrelLines: string[] = [
    "// Generated by @svg-animated-icons/icons. Do not edit.",
    "",
  ];

  for (const entry of entries) {
    const component = toComponentName(entry.name);
    const code = renderIconForFramework(entry, spec.framework);
    const file = join(iconsDir, `${entry.name}.${spec.iconExt}`);
    await writeFile(file, code);
    barrelLines.push(spec.barrelLine(entry, component));
  }

  barrelLines.push("");
  const barrel = join(spec.dir, spec.barrelPath);
  await mkdir(dirname(barrel), { recursive: true });
  await writeFile(barrel, barrelLines.join("\n"));

  console.log(`✓ ${spec.framework}: ${entries.length} icons → ${spec.dir}`);
}

async function main(): Promise<void> {
  const entries = await loadRegistry();
  await Promise.all(PACKAGES.map((spec) => generatePackage(spec, entries)));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
